############################################################
#
# article静态化微服务
# web访问端口号  约定：8002
#
############################################################
server:
#  port: 8002
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

############################################################
#
# 配置项目信息
#
############################################################
spring:
  profiles:
    active: dev  #yml中配置文件的环境设置 dev,test,prod
  application:
    name: service-article-html
  data:
    mongodb:
      uri: mongodb://root:2000127y@172.16.53.132:27017
      database: news-dev
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: org.mariadb.jdbc.Driver          # mysql驱动
    url: jdbc:mysql://localhost:3306/news-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 2000127y
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  freemarker:
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    template-loader-path: classpath:/templates/
  rabbitmq:
    host: 172.16.53.132
    port: 5672
    username: admin
    password: admin
    virtual-host: imooc-news

############################################################
#
# fastdfs的配置信息
#
############################################################
fdfs:
  connect-timeout: 30 #连接时间
  so-timeout: 30 #读取时间
  tracker-list: 172.16.53.128:22122

#定义freemarker的html生成位置
freemarker:
  html:
    target: /Users/Shared/freemarker
    article: /Users/falcon/Desktop/apache-tomcat-9.0.70/webapps/imooc-news/portal/a

