server:
  port: 8001

spring:
  redis:
    port: 6379
    database: 0
    password: 123456
    host: 172.16.53.128

# 设置域名，在Java代码中获取，这里是资源配置
website:
  domain-name: imoocnews.com

#dev环境开启mybatis日志打印
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl